services:
  signaling-server:
    build:
      context: ./signaling-server
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./signaling-server:/app
      - ${SSL_CERT_PATH}:${SSL_CERT_PATH}
      - ${SSL_KEY_PATH}:${SSL_KEY_PATH}
    env_file:
      - .env

  httpd-server:
    build:
      context: ./http-server
    ports:
      - 80:80
      - 443:443
    working_dir: /app
    volumes:
      - ${SSL_CERT_PATH}:/usr/local/apache2/conf/server.crt
      - ${SSL_KEY_PATH}:/usr/local/apache2/conf/server.key
      - ./http-server:/app
    env_file:
      - .env
