services:
    signaling-server:
      build:
        context: ./signaling-server
      ports:
       - 51337:51337
      working_dir: /app
      volumes:
        - ./signaling-server:/app
        - /etc/letsencrypt/live/informatichiens.com/fullchain.pem:/etc/ssl/fullchain.pem
        - /etc/letsencrypt/live/informatichiens.com/privkey.pem:/etc/ssl/privkey.pem
      env_file:
        - ./signaling-server/.env

    httpd-server:
      build:
        context: ./http-server
      ports:
        - 80:80
        - 443:443
      working_dir: /app
      volumes:
        - ./http-server:/app
      env_file:
        - ./http-server/.env
      